# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-13 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpositionTitle', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u044b\u0441\u0442\u0430\u0432\u043a\u0438', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043e\u043f\u0440\u043e\u0432\u043e\u0436\u0434\u0430\u044e\u0449\u0435\u0439 \u0432\u044b\u0441\u0442\u0430\u0432\u043a\u0438')),
                ('HasPoster', models.BooleanField(default=False, verbose_name='\u0411\u044b\u043b\u0430 \u043b\u0438 \u043f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043b\u0435\u043d\u0430 \u0430\u0444\u0438\u0448\u0430?')),
                ('HasPhotos', models.BooleanField(default=False, verbose_name='\u041c\u0435\u0441\u0442\u043e \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u043c\u0435\u0434\u0438\u0430-\u043e\u0442\u0447\u0435\u0442\u0430')),
                ('StartDate', models.DateTimeField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('EndDate', models.DateTimeField(verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('Title', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('Description', models.TextField(help_text='\u041e\u043f\u0438\u0448\u0438\u0442\u0435 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u0435', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u044f \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('Author', models.CharField(help_text='\u0424\u0418\u041e \u043e\u043f\u0435\u0440\u0430\u0442\u043e\u0440\u0430, \u043f\u043e \u0434\u0430\u043d\u043d\u044b\u043c \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438', max_length=255, verbose_name='\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('Location', models.CharField(help_text='\u0414\u0432\u043e\u0440, \u0443\u0441\u0430\u0434\u044c\u0431\u0430, \u0443\u043b\u0438\u0446\u0430 \u0438 etc.', max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0438\u0434\u0435\u043d\u0438\u044f')),
                ('VisitorCount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
                ('ChildVisitorCount', models.IntegerField(verbose_name='.. \u0438\u0437 \u043d\u0438\u0445 \u0434\u0435\u0442\u0435\u0439 14 \u043b\u0435\u0442')),
                ('JuniorVisitorCount', models.IntegerField(verbose_name='..\u043e\u0442 14 \u0434\u043e 18 \u043b\u0435\u0442')),
                ('BooksOnDisplayCount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u044b\u0441\u0442\u0430\u0432\u0432\u043b\u0435\u043d\u044b\u0445 \u043a\u043d\u0438\u0433')),
                ('IssuedBooksCount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u044b\u0434\u0430\u043d\u043d\u044b\u0445 \u043a\u043d\u0438\u0433')),
                ('Department', models.ForeignKey(help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437 \u0441\u043f\u0438\u0441\u043a\u0430', on_delete=django.db.models.deletion.CASCADE, to='sounbs_api.Department', verbose_name='\u041e\u0442\u0434\u0435\u043b-\u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0442\u043e\u0440')),
            ],
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='EventForm',
            field=models.ForeignKey(help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437 \u0441\u043f\u0438\u0441\u043a\u0430', on_delete=django.db.models.deletion.CASCADE, to='sounbs_api.EventForm', verbose_name=''),
        ),
        migrations.AddField(
            model_name='event',
            name='EventType',
            field=models.ForeignKey(help_text='\u041c\u0430\u0441\u0441\u043e\u0432\u043e\u0435 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u0435', on_delete=django.db.models.deletion.CASCADE, to='sounbs_api.EventType', verbose_name='\u0422\u0438\u043f \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='event',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041e\u043f\u0435\u0440\u0430\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='event',
            name='Theme',
            field=models.ForeignKey(help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437 \u0441\u043f\u0438\u0441\u043a\u0430', on_delete=django.db.models.deletion.CASCADE, to='sounbs_api.Theme', verbose_name='\u0422\u0435\u043c\u0430 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f'),
        ),
    ]
